#!/usr/bin/env python3
"""
council/local.py — single-player deep research, one command (D16)
==================================================================
    python -m council.local "your brief"            # or: pw research "your brief"
    python -m council.local "brief" --quick|--deep
    python -m council.local "brief" --editor api    # BYOK frontier editor over LOCAL findings

Everything runs on THIS machine: it plans queries, researches the live web from YOUR
connection, runs multiple installed Ollama models as independent analysts, and the
strongest model (the blind editor) compiles a cited markdown report saved to ./reports/.
Private by construction: no account, no server, no telemetry — only the web searches
leave the machine. Models hold zero tool privileges (they return text; Python acts).

The network (council/net/) is the optional multiplayer mode — this command needs none of it.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import pathlib
import re
import sys
import time

import requests

from council.judge import Judge, _extract_json
from council.researcher import ResearchWorker
from council.sanitize import sanitize_brief
from council.worker import Answer
from council import paths


class Cancelled(Exception):
    """Raised to stop a run at an analyst boundary when the caller (e.g. the desk) cancels."""


OLLAMA = os.environ.get("PW_OLLAMA_BASE", "http://localhost:11434")
# families give genuinely different inference trajectories — pick analysts across them
_FAMILIES = ("qwen", "gemma", "llama", "mistral", "phi", "deepseek", "granite")
_EXCLUDE = ("embed", "vision", "image")


def _make_emit(on_progress):
    def emit(msg: str) -> None:
        # stderr, not stdout: keeps the MCP stdio JSON-RPC channel clean (still shown in terminals)
        print(f"  {msg}", file=sys.stderr, flush=True)
        if on_progress:
            try:
                on_progress(msg)
            except Exception:
                pass
    return emit


def detect_models() -> list[dict]:
    try:
        r = requests.get(f"{OLLAMA}/api/tags", timeout=10)
        r.raise_for_status()
    except requests.exceptions.RequestException as exc:
        # The #1 first-run failure: Ollama installed but not running. Give a fix, not a traceback.
        raise SystemExit(
            f"Can't reach Ollama at {OLLAMA}. Is it running? Start it with `ollama serve`, then "
            f"`ollama pull qwen3:14b` (any decent model). [{type(exc).__name__}]")
    models = [m for m in r.json().get("models", [])
              if not any(x in m["name"].lower() for x in _EXCLUDE)]
    # On CPU-only / constrained machines big models crawl (3-6 tok/s) — let users cap
    # the cast by size: PW_MODEL_CAP_GB=3 keeps only models whose weights fit that budget.
    cap = float(os.environ.get("PW_MODEL_CAP_GB", "0") or 0)
    if cap > 0:
        capped = [m for m in models if m.get("size", 0) <= cap * 1e9]
        models = capped or models[:1]      # never end up with zero models
    if not models:
        raise SystemExit("No usable Ollama models found. Try: ollama pull qwen3:14b")
    return sorted(models, key=lambda m: m.get("size", 0))


def pick_cast(models: list[dict], n_analysts: int = 3) -> tuple[list[str], str]:
    """Analysts = up to N models across different families (diversity reduces correlated
    error); editor/judge = the largest model installed (the quality anchor)."""
    editor = models[-1]["name"]
    by_family: dict[str, str] = {}
    for m in reversed(models):                    # biggest of each family first
        fam = next((f for f in _FAMILIES if f in m["name"].lower()), m["name"].split(":")[0])
        by_family.setdefault(fam, m["name"])
    analysts = list(by_family.values())[:n_analysts]
    if not analysts:
        analysts = [editor]
    return analysts, editor


class _ApiEditor(Judge):
    """BYOK Tier-3: the same editor prompts, generated by a frontier model the USER chose.
    Only locally-gathered findings are sent — never raw pages, never local files."""

    def __init__(self, model: str, api_key: str, url: str):
        super().__init__(model=model)
        self._key, self._url = api_key, url

    def _generate(self, prompt: str, num_predict=None) -> str:
        r = requests.post(self._url, headers={"Authorization": f"Bearer {self._key}"},
                          json={"model": self.model,
                                "messages": [{"role": "user", "content": prompt}],
                                "max_tokens": num_predict or 900}, timeout=120)
        r.raise_for_status()
        return (r.json()["choices"][0]["message"]["content"] or "").strip()


def plan_angles(brief: str, planner_model: str, k: int) -> list[str]:
    """STORM-lite: one cheap call on the SMALLEST model discovers K distinct perspectives;
    each analyst then researches the brief through its own angle (question diversity on
    top of model diversity). Empty list on failure — analysts research angle-less."""
    if k < 2:
        return []
    try:
        r = requests.post(f"{OLLAMA}/api/generate", json={
            "model": planner_model,
            "prompt": ("Identify exactly "
                       f"{k} DISTINCT angles for researching this brief — different lenses "
                       "that together cover it (e.g. regulatory, costs/economics, "
                       "practitioner experience, recent developments — pick what fits THIS "
                       'brief). Reply STRICT JSON only: ["angle one","angle two",…]\n\n'
                       f"BRIEF:\n{brief}\n\nJSON:"),
            "stream": False, "options": {"temperature": 0.3, "num_predict": 160},
            "keep_alive": os.environ.get("PW_OLLAMA_KEEP_ALIVE", "30m")},  # warm the planner (R17)
            timeout=float(os.environ.get("PW_OLLAMA_TIMEOUT", "300")))
        r.raise_for_status()
        parsed = _extract_json((r.json().get("response") or "").strip())
        angles = [str(a).strip() for a in parsed if str(a).strip()] if isinstance(parsed, list) else []
        return angles[:k]
    except Exception:
        return []


def fix_dangling_citations(text: str) -> str:
    """Drop [S#]/[L#] markers that don't resolve to a listed source (web [S#] or local
    document [L#]); the source lists are appended inline so the check is local to the block."""
    listed = set(re.findall(r"^\[([SL]\d+)\]", text, re.MULTILINE))
    if not listed:
        return text
    return re.sub(r"\[([SL]\d+)(?:,\s*(?:[SL]\d+\s*)+)?\]",
                  lambda m: m.group(0) if m.group(1) in listed else "", text)


def _report_payload(brief, depth, editor_label, report, contributions, total_src) -> dict:
    """Machine-readable view of a finished run (report + dedup'd sources + per-analyst stats). Every
    field is already in memory — this just shapes it for `--json`/`--html` and programmatic callers."""
    seen: set[str] = set()
    sources: list[dict] = []
    for c in contributions:
        research = c["research"]
        for s in research.get("sources", []):              # web sources (carry a url + host)
            u = s.get("url")
            if u and u not in seen:
                seen.add(u)
                sources.append({"id": s.get("id"), "title": s.get("title"),
                                "url": u, "host": s.get("host"), "kind": "web"})
        for s in research.get("local_sources", []):        # library [L#] provenance (no url, D48 review)
            key = s.get("source") or s.get("title")
            if key and key not in seen:
                seen.add(key)
                sources.append({"id": s.get("id"), "title": s.get("title"),
                                "source": s.get("source"), "kind": "library"})
    return {
        "brief": brief,
        "generated": datetime.date.today().isoformat(),
        "depth": depth,
        "editor": editor_label,
        "words": len(report.split()),
        "n_sources": len(sources),                         # web + library, deduped
        "analysts": [{"model": c["model"], "words": len(c["text"].split()),
                      "n_sources": len(c["research"].get("sources", []))
                      + len(c["research"].get("local_sources", []))} for c in contributions],
        "sources": sources,
        "report": report,
    }


def run(brief: str, depth: str = "standard", editor_mode: str = "local",
        out_dir: str | None = None, n_analysts: int = 3, scope: str = "both",
        on_progress=None, should_cancel=None, as_json: bool = False,
        as_html: bool = False) -> pathlib.Path:
    t0 = time.monotonic()
    emit = _make_emit(on_progress)
    brief = sanitize_brief(brief)                      # the one user input → clean + length-bound
    if not brief:
        raise ValueError("empty brief — give something to research")
    # Pre-flight the paid editor path BEFORE spending 5-15 min on local research, not after (D48):
    # `--editor api` with no key used to burn the whole local run and only then raise.
    if editor_mode == "api" and not (os.environ.get("OPENROUTER_API_KEY")
                                     or os.environ.get("PW_BASELINE_API_KEY")):
        raise SystemExit("--editor api needs OPENROUTER_API_KEY (or PW_BASELINE_API_KEY) — "
                         "set it before the run")
    os.environ.setdefault("PW_WEB_BACKEND", "ddgs")   # live web ON — the whole point

    models = detect_models()
    analysts, editor_model = pick_cast(models, n_analysts)
    emit(f"🔬 Deep research ({depth}) — analysts: {', '.join(analysts)} · editor: "
         f"{editor_model if editor_mode == 'local' else editor_mode}")

    # STORM-lite perspective planning: distinct angle per analyst (smallest model plans)
    angles = plan_angles(brief, models[0]["name"], len(analysts))
    if angles:
        emit("angles: " + " | ".join(angles))
    page_evidence = not float(os.environ.get("PW_MODEL_CAP_GB", "0") or 0)  # CPU-capped → snippets

    contributions, answers = [], []
    for i, model in enumerate(analysts, 1):
        if should_cancel and should_cancel():          # cooperative cancel at each analyst boundary
            raise Cancelled()
        angle = angles[i - 1] if i <= len(angles) else ""
        emit(f"[{i}/{len(analysts)}] {model} researching the live web…"
             + (f" (angle: {angle})" if angle else ""))
        t = time.monotonic()
        rw = ResearchWorker(worker_id=model, model=model, lens="independent analyst",
                            country=os.environ.get("PW_COUNTRY", "your location"),
                            depth=depth, angle=angle, page_evidence=page_evidence, scope=scope,
                            ollama_base=OLLAMA)   # same endpoint as detection (honors PW_OLLAMA_BASE)
        out = rw.research(brief)
        text = fix_dangling_citations(out["text"])
        nsrc = len(out["research"]["sources"])
        emit(f"    {nsrc} sources · {len(text.split())} words · {time.monotonic()-t:.0f}s")
        contributions.append({"country": model.split(":")[0], "model": model,
                              "lens": "analyst", "text": text,
                              "research": out["research"]})
        answers.append(Answer(worker_id=model, model=model, lens="analyst",
                              country=model.split(":")[0], text=text, tokens=out["tokens"],
                              elapsed_s=out["elapsed_s"]))

    if should_cancel and should_cancel():
        raise Cancelled()
    emit("blind judge + editor compiling the report…")
    if editor_mode == "local":
        judge = Judge(model=editor_model, ollama_base=OLLAMA)   # honors PW_OLLAMA_BASE
    else:
        key = os.environ.get("OPENROUTER_API_KEY") or os.environ.get("PW_BASELINE_API_KEY")
        if not key:
            raise SystemExit("--editor api needs OPENROUTER_API_KEY (or PW_BASELINE_API_KEY)")
        judge = _ApiEditor(os.environ.get("PW_EDITOR_MODEL", "openai/gpt-5-chat"), key,
                           os.environ.get("PW_BASELINE_API_URL",
                                          "https://openrouter.ai/api/v1/chat/completions"))
    read = judge.deliberate(brief, answers)
    report = judge.compile_report(brief, contributions, read, local=True)
    if should_cancel and should_cancel():
        # cancel arrived during the (often longest) editor/judge phase — honor it by discarding the
        # report rather than persisting and returning a run the user explicitly cancelled. (Interrupting
        # the editor call mid-generation would need a cancel hook inside Judge — a later refinement.)
        raise Cancelled()

    out_path = pathlib.Path(out_dir) if out_dir else paths.reports_dir()
    out_path.mkdir(parents=True, exist_ok=True)   # allow nested --out a/b/c; shared ~/.passiveworkers/reports
    # a non-Latin brief (Arabic/CJK/Cyrillic) slugs to empty → fall back to a dated 'report' name
    slug = re.sub(r"[^a-z0-9]+", "-", brief.lower())[:60].strip("-") or "report"
    fname = out_path / f"{datetime.date.today().isoformat()}-{slug}.md"
    n = 1
    while fname.exists():
        n += 1
        fname = out_path / f"{datetime.date.today().isoformat()}-{slug}-{n}.md"
    fname.write_text(report)
    mins = (time.monotonic() - t0) / 60
    total_src = sum(len(c["research"]["sources"]) for c in contributions)
    if as_json or as_html:
        editor_label = editor_model if editor_mode == "local" else editor_mode
        payload = _report_payload(brief, depth, editor_label, report, contributions, total_src)
        if as_json:
            fname.with_suffix(".json").write_text(json.dumps(payload, ensure_ascii=False, indent=2))
            emit(f"🧾 JSON → {fname.with_suffix('.json')}")
        if as_html:
            from council import render
            fname.with_suffix(".html").write_text(render.report_html(brief, report, payload))
            emit(f"🖨  HTML (printable) → {fname.with_suffix('.html')}")
    emit(f"📄 Report ready in {mins:.1f} min · {len(report.split())} words · "
         f"{total_src} sources → {fname}")
    return fname


def main() -> int:
    p = argparse.ArgumentParser(prog="pw research",
                                description="Local-first deep research with your own models.")
    p.add_argument("brief", help="what should be researched")
    p.add_argument("--quick", action="store_true", help="1 research round (fastest)")
    p.add_argument("--deep", action="store_true", help="extra research rounds")
    p.add_argument("--editor", choices=["local", "api"], default="local",
                   help="api = BYOK frontier editor over local findings (OPENROUTER_API_KEY)")
    p.add_argument("--analysts", type=int, default=3, help="how many local models analyze (1-4)")
    p.add_argument("--out", default=None,
                   help="output directory (default: ~/.passiveworkers/reports, shared with the desk)")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--local", action="store_true", help="research ONLY your library (no web)")
    g.add_argument("--web", action="store_true", help="research ONLY the live web (no library)")
    p.add_argument("--json", action="store_true",
                   help="also write <report>.json (report + sources + per-analyst) and print it to stdout")
    p.add_argument("--html", action="store_true", help="also write a styled, printable <report>.html")
    a = p.parse_args()
    depth = "quick" if a.quick else "deep" if a.deep else "standard"
    scope = "local" if a.local else "web" if a.web else "both"
    try:
        path = run(a.brief, depth=depth, editor_mode=a.editor, out_dir=a.out,
                   n_analysts=max(1, min(4, a.analysts)), scope=scope,
                   as_json=a.json, as_html=a.html)
    except KeyboardInterrupt:
        print("\n  interrupted — partial research discarded.", file=sys.stderr)
        return 130
    if a.json:
        # progress goes to stderr, so stdout is clean → `pw research "…" --json > out.json` works
        print(pathlib.Path(path).with_suffix(".json").read_text())
    return 0


if __name__ == "__main__":
    sys.exit(main())
