#!/usr/bin/env python3
"""
council/render.py — a cited markdown report → a self-contained, printable HTML page
===================================================================================
No dependencies: a small, safe markdown subset (headings, bold, links, bullet lists, paragraphs)
so ``pw research --html`` and the desk's "Save as PDF" work everywhere, and the output is ONE
portable file (inline CSS, no external assets). Everything is HTML-escaped before transforms, so a
report can never inject markup — the same XSS discipline the served UIs use.
"""

from __future__ import annotations

import html as _html
import re

_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_URL = re.compile(r"https?://[^\s<\]]+")


def _linkify(m: "re.Match") -> str:
    url = m.group(0)
    trail = ""
    # A URL may legitimately END in ')' — Wikipedia disambiguation pages like Mercury_(planet) —
    # so trim only an UNBALANCED trailing ')' and ordinary sentence punctuation, keeping balanced parens.
    while url and url[-1] in ").,;:!?":
        if url[-1] == ")" and url.count("(") >= url.count(")"):
            break
        trail = url[-1] + trail
        url = url[:-1]
    return f'<a href="{url}" target="_blank" rel="noopener">{url}</a>{trail}'


def _inline(escaped: str) -> str:
    s = _BOLD.sub(r"<strong>\1</strong>", escaped)
    return _URL.sub(_linkify, s)


def md_to_html(text: str) -> str:
    """Render the markdown subset the engine emits. Input is escaped FIRST, then transformed."""
    out: list[str] = []
    in_list = False
    for raw in (text or "").split("\n"):
        line = raw.rstrip()
        m_h = re.match(r"(#{1,4})\s+(.*)", line)
        m_li = re.match(r"[-•]\s+(.*)", line)
        if m_li:
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_inline(_html.escape(m_li.group(1)))}</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        if m_h:
            lvl = len(m_h.group(1))
            out.append(f"<h{lvl}>{_inline(_html.escape(m_h.group(2)))}</h{lvl}>")
        elif line:
            out.append(f"<p>{_inline(_html.escape(line))}</p>")
    if in_list:
        out.append("</ul>")
    return "\n".join(out)


_DOC = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>__TITLE__ — Passive Workers</title>
<style>
:root{color-scheme:light dark}
body{max-width:760px;margin:2rem auto;padding:0 1.2rem;
  font:16px/1.65 -apple-system,Segoe UI,Roboto,Georgia,serif;color:#1a1a1a;background:#fff}
@media(prefers-color-scheme:dark){body{color:#e6e6e6;background:#14161c}a{color:#7db3ff}
  .pw-meta,.pw-foot{color:#9aa}}
h1{font-size:1.7rem;line-height:1.25;margin:.2rem 0 .6rem}
h2{font-size:1.3rem;margin:1.6rem 0 .4rem} h3,h4{font-size:1.08rem;margin:1.2rem 0 .3rem}
a{color:#2457d6;word-break:break-word} ul{padding-left:1.3rem} li{margin:.2rem 0}
.pw-meta{color:#888;font-size:.85rem;margin:0 0 1.6rem}
.pw-foot{margin-top:2.5rem;padding-top:1rem;border-top:1px solid #ddd;color:#999;font-size:.8rem}
@media print{a{color:inherit;text-decoration:none}body{margin:0;max-width:none}}
</style></head><body>
<div class="pw-meta">__META__</div>
__BODY__
<div class="pw-foot">Generated by Passive Workers — local-first deep research. Your models, your connection, your disk.</div>
</body></html>
"""


def report_html(title: str, report_md: str, meta: dict | None = None) -> str:
    """A complete, self-contained HTML document for a report. `title`/`meta` are escaped; the
    rendered body is trusted markup produced by md_to_html (which escapes its own input)."""
    meta = meta or {}
    sub = (f"{meta.get('n_sources', '?')} sources · {meta.get('words', '?')} words"
           f" · {meta.get('generated', '')}").strip(" ·")
    parts = {"__TITLE__": _html.escape((title or "report")[:120]),
             "__META__": _html.escape(sub),
             "__BODY__": md_to_html(report_md)}
    # single-pass substitution: a value that itself contains a placeholder (e.g. a brief with the
    # literal "__BODY__") can't leak the report into the <title>, because replacements aren't re-scanned.
    return re.sub("__TITLE__|__META__|__BODY__", lambda m: parts[m.group(0)], _DOC)
